"""
AIBET MVP Database Models
SQLAlchemy models for SQLite database
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, Boolean, Text, ForeignKey, JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
from typing import Optional

Base = declarative_base()

class Team(Base):
    """Team information"""
    __tablename__ = "teams"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False, index=True)
    sport = Column(String(20), nullable=False, index=True)  # cs2, khl
    country = Column(String(50))
    rating = Column(Float, default=1500)  # ELO-like rating
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    home_matches = relationship("Match", foreign_keys="Match.team1_id", back_populates="team1")
    away_matches = relationship("Match", foreign_keys="Match.team2_id", back_populates="team2")
    team_stats = relationship("TeamStats", back_populates="team")
    
    def __repr__(self):
        return f"<Team(name='{self.name}', sport='{self.sport}', rating={self.rating})>"

class Match(Base):
    """Historical and upcoming matches"""
    __tablename__ = "matches"
    
    id = Column(Integer, primary_key=True, index=True)
    team1_id = Column(Integer, ForeignKey("teams.id"), nullable=False)
    team2_id = Column(Integer, ForeignKey("teams.id"), nullable=False)
    sport = Column(String(20), nullable=False, index=True)
    date = Column(DateTime, nullable=False, index=True)
    tournament = Column(String(100))
    result = Column(String(10), index=True)  # team1, team2, draw, upcoming
    score = Column(String(20))  # 16-14, 3-2, etc.
    best_of = Column(Integer)  # 1, 3, 5
    map_name = Column(String(50))  # for CS2
    arena = Column(String(100))  # for KHL
    is_upcoming = Column(Boolean, default=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    team1 = relationship("Team", foreign_keys=[team1_id], back_populates="home_matches")
    team2 = relationship("Team", foreign_keys=[team2_id], back_populates="away_matches")
    predictions = relationship("Prediction", back_populates="match")
    
    def __repr__(self):
        return f"<Match(id={self.id}, sport='{self.sport}', result='{self.result}')>"

class TeamStats(Base):
    """Team statistics for ML features"""
    __tablename__ = "team_stats"
    
    id = Column(Integer, primary_key=True, index=True)
    team_id = Column(Integer, ForeignKey("teams.id"), unique=True, nullable=False)
    sport = Column(String(20), nullable=False)
    
    # Basic stats
    matches_played = Column(Integer, default=0)
    wins = Column(Integer, default=0)
    losses = Column(Integer, default=0)
    draws = Column(Integer, default=0)
    
    # Form (last N matches)
    recent_form = Column(JSON)  # ["W", "L", "W", "D", "W"]
    
    # Sport-specific stats
    cs2_map_winrate = Column(JSON)  # {"mirage": 0.65, "dust2": 0.58}
    khl_home_away = Column(JSON)  # {"home": {"wins": 15, "losses": 5}, "away": {"wins": 10, "losses": 10}}
    
    # Advanced stats
    avg_score_for = Column(Float, default=0)
    avg_score_against = Column(Float, default=0)
    win_rate = Column(Float, default=0)
    
    # H2H stats
    h2h_vs_team = Column(JSON)  # {"team_id": {"wins": 5, "losses": 3, "draws": 2}}
    
    updated_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    team = relationship("Team", back_populates="team_stats")
    
    def __repr__(self):
        return f"<TeamStats(team_id={self.team_id}, win_rate={self.win_rate})>"

class Signal(Base):
    """Betting signals generated by ML"""
    __tablename__ = "signals"
    
    id = Column(Integer, primary_key=True, index=True)
    match_id = Column(Integer, ForeignKey("matches.id"), nullable=False)
    sport = Column(String(20), nullable=False, index=True)
    
    # Signal details
    prediction = Column(String(10), nullable=False)  # team1, team2, draw
    probability = Column(Float, nullable=False)  # 0.0 to 1.0
    confidence = Column(Float, nullable=False)  # 0 to 100
    value_score = Column(Float)  # value vs implied odds
    
    # Signal metadata
    model_version = Column(String(20))
    features_used = Column(JSON)
    explanation = Column(Text)  # Human-readable explanation
    
    # Status
    is_active = Column(Boolean, default=True, index=True)
    is_published = Column(Boolean, default=False)
    result = Column(String(10))  # win, loss, pending
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    match = relationship("Match")
    
    def __repr__(self):
        return f"<Signal(id={self.id}, prediction='{self.prediction}', confidence={self.confidence})>"

class ModelMetrics(Base):
    """ML model performance metrics"""
    __tablename__ = "model_metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    sport = Column(String(20), nullable=False)
    model_name = Column(String(50), nullable=False)
    model_version = Column(String(20))
    
    # Performance metrics
    accuracy = Column(Float)
    precision = Column(Float)
    recall = Column(Float)
    f1_score = Column(Float)
    roc_auc = Column(Float)
    
    # Training info
    training_samples = Column(Integer)
    test_samples = Column(Integer)
    features_count = Column(Integer)
    
    # Metadata
    training_date = Column(DateTime)
    last_updated = Column(DateTime, default=datetime.utcnow)
    
    def __repr__(self):
        return f"<ModelMetrics(model='{self.model_name}', accuracy={self.accuracy})>"

class Prediction(Base):
    """Individual predictions for tracking"""
    __tablename__ = "predictions"
    
    id = Column(Integer, primary_key=True, index=True)
    match_id = Column(Integer, ForeignKey("matches.id"), nullable=False)
    signal_id = Column(Integer, ForeignKey("signals.id"))
    sport = Column(String(20), nullable=False)
    
    # Prediction details
    predicted_outcome = Column(String(10))
    actual_outcome = Column(String(10))
    probability = Column(Float)
    was_correct = Column(Boolean)
    
    # Model info
    model_name = Column(String(50))
    model_version = Column(String(20))
    
    created_at = Column(DateTime, default=datetime.utcnow)
    resolved_at = Column(DateTime)
    
    # Relationships
    match = relationship("Match", back_populates="predictions")
    signal = relationship("Signal")
    
    def __repr__(self):
        return f"<Prediction(match_id={self.match_id}, correct={self.was_correct})>"
